FROM gradle:9.7.0-jdk25

# Prevent collisions with remote user
RUN usermod -u 999 gradle
RUN groupmod -g 999 gradle

ARG REMOTE_USER
ARG REMOTE_UID
ARG REMOTE_GID

RUN groupadd --gid $REMOTE_GID $REMOTE_USER
RUN useradd --uid $REMOTE_UID --gid $REMOTE_GID -s /bin/bash -m $REMOTE_USER

USER $REMOTE_USER
